#!/bin/sh

force_stop() {
  docker stop $1 &> /dev/null
  docker rm $1 &> /dev/null
}


inspect() {
  if hash boot2docker 2>/dev/null; then
    boot2docker ssh docker inspect --format=$2 $1
  else
    docker inspect --format=$2 $1
  fi
}


get_ip() {
  if hash boot2docker 2>/dev/null; then
    boot2docker ip 2>/dev/null
  else
    docker inspect --format={{.NetworkSettings.IPAddress}} $1
  fi
}


run() {
  container_id=$(docker run "$@")
  local status=$?
  if [ $status -ne 0 ]; then
    echo >&2
    echo "Failed to start the Docker container." >&2
    exit 1
  fi

  container_name=$(inspect $container_id '{{.Name}}')
  # strip the leading / character
  container_name=${container_name#?}

  container_ip=$(get_ip $container_id)

  host_ports=$(inspect $container_id '' | \
                 grep HostPort | \
                 sed 's/[^0-9]*//g' | \
                 sort -nu)

  echo "Container $container_name started"
  echo "IP:      $container_ip"
  echo "Ports:   $(echo $host_ports | tr '\\n' ',')"
}
