#!/bin/sh
#
# Script for easily running development systems in docker containers
# https://github.com/bripkens/dock
#

remote_repo=https://github.com/bripkens/dock.git
local_repo=$HOME/.dock


version() {
  echo "$(basename $0) 0.1.0 by Ben Ripkens <bripkens.dev@gmail.com>"
  echo "https://github.com/bripkens/dock"
}


usage() {
    version
cat << EOF >&2

TODO...

Usage:
    $(basename $0) [options]
    $(basename $0) [program]

Example:
    $(basename $0) redis

Options:
    -l, --list          List available boilerplates
    -u, --upgrade       Upgrade list of available boilerplates
    -h, --help          Display this help text
    -v, --version       Display current script version
EOF
}


clone() {
  if [ $1 -a $1 = '--silently' ]; then
    git clone -q "$remote_repo" "$local_repo"
  else
    echo "Cloning $remote_repo to $local_repo"
    git clone "$remote_repo" "$local_repo"
  fi
}


upgrade() {
  if [ ! -e "$local_repo/.git" ]; then
    clone
  else
    cd "$local_repo"
    git pull origin master
  fi
}


init() {
  if [ ! -e "$local_repo/.git" ]; then
    clone $1
  fi
}


list() {
  init

  echo "Programs:"
  echo
  for path in $(ls "$local_repo"/programs | sort -f); do
    filename=$(basename $path)
    echo "${filename%.*}"
  done
}


# Parse comand-line options
while [ $# -gt 0 ]; do
  case $1 in
    -v | --version )
      version
      exit 1
      ;;
    -l | --list )
      list
      ;;
    -u | --upgrade )
      upgrade
      ;;
    -h | --help )
      usage
      exit 1
      ;;
    * ) # default case
      dump $1
      ;;
  esac
  shift
done
