#!/bin/bash

source "${BASH_SOURCE%/*}/../common"

force_stop dock-apacheds

run --detach \
    --publish 10389:10389 \
    --name dock-apacheds \
    jjhughes57/apacheds-docker

echo "Admin user:     uid=admin,ou=system"
echo "Admin pw:       secret"
