#!/bin/bash

source "${BASH_SOURCE%/*}/../common"

force_stop dock-artifactory

run --detach \
    --publish 8473:8081 \
    --name dock-artifactory \
    jfrog-docker-registry.bintray.io/jfrog/artifactory-oss
