#!/bin/bash

echo '
# Starting an interactive Docker container which contains the
# CLI tools. Inspect the env to learn about IPs and ports.
# Kafka is located at $KAFKA_HOME.'

docker run --interactive \
           --tty \
           --link dock-zookeeper:zk \
           --link dock-kafka-1:kafka-1 \
           --link dock-kafka-2:kafka-2 \
           --link dock-kafka-3:kafka-3 \
           wurstmeister/kafka:0.8.1.1-1 \
           bash
