#!/bin/bash

docker run --interactive \
           --tty \
           --rm \
           --link dock-mysql:mysql \
           mysql \
           sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD"'
