#!/bin/bash

source "${BASH_SOURCE%/*}/../common"

force_stop dock-mysql

root_pw="root"

run --detach \
    --env MYSQL_ROOT_PASSWORD=$root_pw \
    --publish 3306:3306 \
    --name dock-mysql \
    mysql

echo "Password:       $root_pw"
