#!/bin/bash

source "${BASH_SOURCE%/*}/../common"

force_stop dock-mysql

root_pw="root"
db="dockDatabase"
user="dockUser"
user_pw="dockPassword"

run --detach \
    --env MYSQL_ROOT_PASSWORD=$root_pw \
    --env MYSQL_USER=$user \
    --env MYSQL_PASSWORD=$user_pw \
    --env MYSQL_DATABASE=$db \
    --publish 3306:3306 \
    --name dock-mysql \
    mysql

echo "Root password:  $root_pw"
echo
echo "Database:       $db"
echo "User:           $user"
echo "User password:  $user_pw"
