#!/bin/bash

source "${BASH_SOURCE%/*}/../common"

force_stop dock-orientdb

run --detach \
    --publish 2424:2424 \
    --publish 2480:2480 \
    --name dock-orientdb \
    joaodubas/orientdb

echo "Admin user:     admin"
echo "Admin pw:       admin"
