#!/bin/bash

source "${BASH_SOURCE%/*}/../common"

force_stop php5-fpm

run --detach \
    --publish 9000 \
    --name php5-fpm \
    --volume $(pwd):/var/www/html \
    php:5-fpm

echo "Mounted $(pwd) into /var/www/html"
