#!/bin/bash

docker run --interactive \
           --tty \
           --rm \
           --link postgres:postgres \
           postgres \
           bash -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres'
