#!/bin/bash

source "${BASH_SOURCE%/*}/../common"

force_stop postgres

run --detach \
    --name postgres \
    --publish 5432:5432 \
    postgres

echo "Default User:   postgres"
echo "Pro Tip:        You can use the postgres CLI via 'dock postgres-cli'."
