#!/bin/bash

source "${BASH_SOURCE%/*}/../common"

force_stop dock-rabbitmq

run --detach \
    --name dock-rabbitmq \
    --publish 5672:5672 \
    --publish 15672:15672 \
    tutum/rabbitmq

echo "Admin user:     admin"
echo "Admin password: Inspect the password via 'docker logs dock-rabbitmq'"
