#!/bin/bash

source "${BASH_SOURCE%/*}/../common"

force_stop sonar-server
force_stop sonar-mysql

run --detach \
    --publish 3306:3306 \
    --name sonar-mysql \
    tpires/sonar-mysql

echo
run --detach \
    --publish 8474:9000 \
    --name sonar-server \
    --link sonar-mysql:db \
    tpires/sonar-server

echo "Admin user:     admin"
echo "Admin pw:       admin"
