#!/bin/bash

source "${BASH_SOURCE%/*}/../common"

force_stop dock-wordpress

run --detach \
    --publish 8686:80 \
    --name dock-wordpress \
    --link dock-mysql:mysql \
    wordpress:latest

echo "Wordpress Database name: wordpress"
echo "Wordpress Database user: root"
